// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzcqahiyuqrxbzhzenzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6Y3FhaGl5dXFyeGJ6aHplbnp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3Mzg3NzQsImV4cCI6MjA2NTMxNDc3NH0.7qQvMJnsXaGD2QNAffRnYTeUTuUDF8W7_7lQQtnMyAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);